### ISSUE TITLE
Deprecation warning with Jasmine-Core@3.3.0

### ISSUE THREAD

**Issue by Lalem001** [karma-runner/karma-jasmine#221] opened 2018-10-25 20:15 UTC
[Jasmine-Core 3.3.0 release nodes](https://github.com/jasmine/jasmine/blob/master/release_notes/3.3.0.md)

> Introduce a configuration object to Env deprecating old single use functions

The test fails as well, however I am not sure if that is something that could be fixed here.

```text
HeadlessChrome 0.0.0 (Mac OS X 10.13.6) ERROR: 'DEPRECATION:', 'Setting specFilter directly on Env is deprecated, please use the specFilter option in `configure`'
HeadlessChrome 0.0.0 (Mac OS X 10.13.6) ERROR
  {
    "message": "TypeError: this.deprecated is not a function\n    at Env.throwOnExpectationFailure (/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1079:12)\n    at setOption (/node_modules/karma-jasmine/lib/adapter.js:354:7)\n    at ContextKarma.start (/node_modules/karma-jasmine/lib/adapter.js:343:5)\n    at ContextKarma.loaded (http://localhost:9876/context.js:168:14)\n    at http://localhost:9876/context.html:47:22",
    "str": "TypeError: this.deprecated is not a function\n    at Env.throwOnExpectationFailure (/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1079:12)\n    at setOption (/node_modules/karma-jasmine/lib/adapter.js:354:7)\n    at ContextKarma.start (/node_modules/karma-jasmine/lib/adapter.js:343:5)\n    at ContextKarma.loaded (http://localhost:9876/context.js:168:14)\n    at http://localhost:9876/context.html:47:22"
  }
HeadlessChrome 0.0.0 (Mac OS X 10.13.6): Executed 0 of 0 ERROR (0.122 secs / 0 secs)
```

**Comment by Lalem001** [comment] 2018-10-26 14:20
After some investigation, it appears the tests failure that results in "this.deprecated is not a function" is caused by `client.jasmine` configuration being set.

For example, setting such properties on this repo's `karma.conf.js` causes the error:

```javascript
module.exports = function (config) {
  config.set({
    frameworks: ['jasmine'],

    files: [
      'src/*.js',
      'test/*.js'
    ],

    browsers: process.env.TRAVIS ? ['Firefox'] : ['Chrome'],

    client: {
      jasmine: {
        random: false,
      }
    },

    autoWatch: true,

    plugins: [
      'karma-firefox-launcher',
      'karma-chrome-launcher',
      require.resolve('./')
    ]
  })
}
```

This does not absolve `karma-jasmine` from updating to the new configuration object. I am looking to see if I can figure out a solution.

**Comment by Lalem001** [comment] 2018-10-26 19:15
@johnjbarton I had a PR up that fixed the issue, but broke support for jasmine < 3.3.0. Do you want to continue supporting such versions?

**Comment by johnjbarton** [comment] 2018-10-26 23:37
Yes, we need a solution where the entire jasmine 3.x series works for a karma-jasmine 2.x.

**Comment by Lalem001** [comment] 2018-10-29 15:15
@johnjbarton Any suggestions on how to get the unit tests to test against the different versions of jasmine?

**Comment by johnjbarton** [comment] 2018-10-29 16:49
>  it appears the tests failure that results in "this.deprecated is not a function" is caused by client.jasmine configuration being set.

We need to run down what exactly is the cause here. Which line of code fails, what is the `this` value on that line, and how is `client.jasmine` related?

I hope the jasmine config spec did not change in v3.3?

**Comment by Lalem001** [comment] 2018-10-29 17:53
The this is incorrect because of Lines [358-361](https://github.com/karma-runner/karma-jasmine/blob/master/src/adapter.js#L358-L361) and Line [372](https://github.com/karma-runner/karma-jasmine/blob/master/src/adapter.js#L372).

#223, resolves the this binding issue. But Jasmine changed the methods that are invoked in these lines to have deprecations notices.

The jasmine confit spec actually has changed with 3.3. 

Karma-Jasmine's `stopOnFailure` pointed to `throwOnExpectationFailure` in jasmines configuration pre 3.3. The new configuration option in Jasmine 3.3 is `oneFailurePerSpec`

I believe I am close to a PR that handles both cases without deprecation warnings.

**Comment by Lalem001** [comment] 2018-10-29 18:01
Regarding my pending PR,

While the code itself can handle Jasmine 3.3, I don't like that I need to have the unit tests change their behavior to handle `Jasmine@>=3.3.0`. Its either branch on the version of jasmine, or have separate sets of unit tests.

**Comment by nasvillanueva** [comment] 2018-10-29 23:17
> I believe I am close to a PR that handles both cases without deprecation warnings.
@Lalem001 why are you targeting the removal of those deprecation warning?

**Comment by tempoc** [comment] 2018-11-01 20:39
For our project it was yarn killing it.
Saw the problem when running `yarn install` which resolved `jasmine-core` to version `3.3.0`.
Fixed by running `npm install` which resolved `jasmine-core` to version `3.2.1`.

**Closed** 2018-11-07 00:47 UTC

**Comment by julmot** [comment] 2018-11-08 18:20
I'm also seeing it with ^3.0.0

**Comment by ShinDarth** [comment] 2018-11-12 14:21
getting the same warning here, using:

```
    "jasmine-core": "^3.3.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^3.1.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^1.0.1",
    "karma-coverage-istanbul-reporter": "^2.0.4",
    "karma-jasmine": "^1.1.2",
    "karma-jasmine-html-reporter": "^1.4.0",
    "karma-junit-reporter": "^1.2.0",
```

**Comment by webmaster128** [comment] 2018-11-12 14:41
Unfortunately the patch from #224 is not released yet

**Comment by cenfun** [comment] 2018-11-15 00:15
Could you please publish new version since it's fixed?

**Comment by johnjbarton** [comment] 2018-11-15 00:45
Please send a Pull Request to update the documentation for the new release.

**Comment by Lalem001** [comment] 2018-11-20 14:18
@johnjbarton Not sure what you are looking for here. The README has a minor update in the PR to remove the invalid configuration value. Are you looking for a section explaining why backward compatibility is lost? And/Or setting the `Jasmine 2.0` header to something like `Jasmine 2.0 - 3.2` and adding a `Jasmine 3.3` header?

**Comment by webmaster128** [comment] 2018-11-20 14:20
@Lalem001 All done now and upgrade possible (see e.g. https://github.com/iov-one/iov-core/pull/542/files)

**Comment by yasiryc** [comment] 2019-01-02 19:58
Any update when the fix would be published? npm still shows 3.3.0 as latest version

**Comment by MauricioPenteado** [comment] 2019-02-13 09:27
I fixed it on my side using the follow upgrades:

"jasmine-core": "^3.3.0",
"karma-jasmine": "^2.0.1",
"karma-jasmine-html-reporter": "^1.4.0",

**Comment by mowali** [comment] 2019-03-08 04:44
MauricioPenteado: I have the exact setup like yours but still sees error.
